els-ASAP auto commit file/tag ocaml-4.05.0-6.el7.src.rpm

diff --git a/src/testsuite/tests/asmcomp/Makefile b/src/testsuite/tests/asmcomp/Makefile
--- a/src/testsuite/tests/asmcomp/Makefile
+++ b/src/testsuite/tests/asmcomp/Makefile
@@ -1,123 +1,46 @@
-#########################################################################
-#                                                                       #
-#                                 OCaml                                 #
-#                                                                       #
-#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
-#                                                                       #
-#   Copyright 2010 Institut National de Recherche en Informatique et    #
-#   en Automatique.  All rights reserved.  This file is distributed     #
-#   under the terms of the Q Public License version 1.0.                #
-#                                                                       #
-#########################################################################
+#**************************************************************************
+#*                                                                        *
+#*                                OCaml                                   *
+#*                                                                        *
+#*                 Xavier Clerc, SED, INRIA Rocquencourt                  *
+#*                                                                        *
+#*   Copyright 2010 Institut National de Recherche en Informatique et     *
+#*     en Automatique.                                                    *
+#*                                                                        *
+#*   All rights reserved.  This file is distributed under the terms of    *
+#*   the GNU Lesser General Public License version 2.1, with the          *
+#*   special exception on linking described in the file LICENSE.          *
+#*                                                                        *
+#**************************************************************************
 
 BASEDIR=../..
 
-CC=$(NATIVECC)
-CFLAGS=$(NATIVECCCOMPOPTS) -g
-
 INCLUDES=\
+  -I $(OTOPDIR)/parsing \
   -I $(OTOPDIR)/utils \
   -I $(OTOPDIR)/typing \
+  -I $(OTOPDIR)/middle_end \
   -I $(OTOPDIR)/bytecomp \
   -I $(OTOPDIR)/asmcomp
 
 OTHEROBJS=\
-  $(OTOPDIR)/utils/misc.cmo \
-  $(OTOPDIR)/utils/tbl.cmo \
-  $(OTOPDIR)/utils/config.cmo \
-  $(OTOPDIR)/utils/clflags.cmo \
-  $(OTOPDIR)/utils/terminfo.cmo \
-  $(OTOPDIR)/utils/ccomp.cmo \
-  $(OTOPDIR)/utils/warnings.cmo \
-  $(OTOPDIR)/utils/consistbl.cmo \
-  $(OTOPDIR)/parsing/location.cmo \
-  $(OTOPDIR)/parsing/longident.cmo \
-  $(OTOPDIR)/parsing/syntaxerr.cmo \
-  $(OTOPDIR)/parsing/parser.cmo \
-  $(OTOPDIR)/parsing/lexer.cmo \
-  $(OTOPDIR)/parsing/parse.cmo \
-  $(OTOPDIR)/parsing/printast.cmo \
-  $(OTOPDIR)/typing/ident.cmo \
-  $(OTOPDIR)/typing/path.cmo \
-  $(OTOPDIR)/typing/primitive.cmo \
-  $(OTOPDIR)/typing/types.cmo \
-  $(OTOPDIR)/typing/btype.cmo \
-  $(OTOPDIR)/typing/oprint.cmo \
-  $(OTOPDIR)/typing/subst.cmo \
-  $(OTOPDIR)/typing/predef.cmo \
-  $(OTOPDIR)/typing/datarepr.cmo \
-  $(OTOPDIR)/typing/cmi_format.cmo \
-  $(OTOPDIR)/typing/env.cmo \
-  $(OTOPDIR)/typing/typedtree.cmo \
-  $(OTOPDIR)/typing/ctype.cmo \
-  $(OTOPDIR)/typing/printtyp.cmo \
-  $(OTOPDIR)/typing/includeclass.cmo \
-  $(OTOPDIR)/typing/mtype.cmo \
-  $(OTOPDIR)/typing/includecore.cmo \
-  $(OTOPDIR)/typing/includemod.cmo \
-  $(OTOPDIR)/typing/parmatch.cmo \
-  $(OTOPDIR)/typing/typetexp.cmo \
-  $(OTOPDIR)/typing/typedtreeMap.cmo \
-  $(OTOPDIR)/typing/cmt_format.cmo \
-  $(OTOPDIR)/typing/stypes.cmo \
-  $(OTOPDIR)/typing/typecore.cmo \
-  $(OTOPDIR)/typing/typedecl.cmo \
-  $(OTOPDIR)/typing/typeclass.cmo \
-  $(OTOPDIR)/typing/typemod.cmo \
-  $(OTOPDIR)/bytecomp/lambda.cmo \
-  $(OTOPDIR)/bytecomp/printlambda.cmo \
-  $(OTOPDIR)/bytecomp/typeopt.cmo \
-  $(OTOPDIR)/bytecomp/switch.cmo \
-  $(OTOPDIR)/bytecomp/matching.cmo \
-  $(OTOPDIR)/bytecomp/translobj.cmo \
-  $(OTOPDIR)/bytecomp/translcore.cmo \
-  $(OTOPDIR)/bytecomp/translclass.cmo \
-  $(OTOPDIR)/bytecomp/translmod.cmo \
-  $(OTOPDIR)/bytecomp/simplif.cmo \
-  $(OTOPDIR)/bytecomp/runtimedef.cmo \
-  $(OTOPDIR)/asmcomp/arch.cmo \
-  $(OTOPDIR)/asmcomp/debuginfo.cmo \
-  $(OTOPDIR)/asmcomp/cmm.cmo \
-  $(OTOPDIR)/asmcomp/printcmm.cmo \
-  $(OTOPDIR)/asmcomp/reg.cmo \
-  $(OTOPDIR)/asmcomp/mach.cmo \
-  $(OTOPDIR)/asmcomp/proc.cmo \
-  $(OTOPDIR)/asmcomp/clambda.cmo \
-  $(OTOPDIR)/asmcomp/compilenv.cmo \
-  $(OTOPDIR)/asmcomp/closure.cmo \
-  $(OTOPDIR)/asmcomp/cmmgen.cmo \
-  $(OTOPDIR)/asmcomp/printmach.cmo \
-  $(OTOPDIR)/asmcomp/selectgen.cmo \
-  $(OTOPDIR)/asmcomp/selection.cmo \
-  $(OTOPDIR)/asmcomp/comballoc.cmo \
-  $(OTOPDIR)/asmcomp/liveness.cmo \
-  $(OTOPDIR)/asmcomp/spill.cmo \
-  $(OTOPDIR)/asmcomp/split.cmo \
-  $(OTOPDIR)/asmcomp/interf.cmo \
-  $(OTOPDIR)/asmcomp/coloring.cmo \
-  $(OTOPDIR)/asmcomp/reloadgen.cmo \
-  $(OTOPDIR)/asmcomp/reload.cmo \
-  $(OTOPDIR)/asmcomp/printlinear.cmo \
-  $(OTOPDIR)/asmcomp/linearize.cmo \
-  $(OTOPDIR)/asmcomp/schedgen.cmo \
-  $(OTOPDIR)/asmcomp/scheduling.cmo \
-  $(OTOPDIR)/asmcomp/emitaux.cmo \
-  $(OTOPDIR)/asmcomp/emit.cmo \
-  $(OTOPDIR)/asmcomp/printclambda.cmo \
-  $(OTOPDIR)/asmcomp/asmgen.cmo
+  $(OTOPDIR)/compilerlibs/ocamlcommon.cma \
+  $(OTOPDIR)/compilerlibs/ocamloptcomp.cma
 
 OBJS=parsecmmaux.cmo parsecmm.cmo lexcmm.cmo
 
-ADD_COMPFLAGS=$(INCLUDES) -g
+ADD_COMPFLAGS=$(INCLUDES) -w -40 -g
 
 default:
-	@if $(BYTECODE_ONLY) || [ -z "$(ASPP)" ]; then : ; else \
+	@if $(BYTECODE_ONLY) || $(SKIP) ; then $(MAKE) skips ; else \
 	  $(MAKE) all; \
 	fi
 
 all:
-	$(MAKE) arch codegen
-	$(MAKE) tests
+	@$(MAKE) arch codegen
+	@$(MAKE) tests
+
+main.cmo: parsecmm.cmo
 
 codegen: parsecmm.ml lexcmm.ml $(OBJS:.cmo=.cmi) $(OBJS) main.cmo
 	@$(OCAMLC) $(LINKFLAGS) -o codegen $(OTHEROBJS) $(OBJS) main.cmo
@@ -128,8 +51,22 @@ parsecmm.mli parsecmm.ml: parsecmm.mly
 lexcmm.ml: lexcmm.mll
 	@$(OCAMLLEX) -q lexcmm.mll
 
+MLCASES=optargs staticalloc bind_tuples is_static register_typing \
+  register_typing_switch
+ARGS_optargs=-g
+ARGS_is_static=-I $(OTOPDIR)/byterun is_in_static_data.c
+MLCASES_FLAMBDA=is_static_flambda unrolling_flambda unrolling_flambda2 \
+  static_float_array_flambda static_float_array_flambda_opaque
+ARGS_is_static_flambda=\
+  -I $(OTOPDIR)/byterun is_in_static_data.c is_static_flambda_dep.ml
+ARGS_static_float_array_flambda=\
+  -I $(OTOPDIR)/byterun is_in_static_data.c simple_float_const.ml
+ARGS_static_float_array_flambda_opaque=\
+  -I $(OTOPDIR)/byterun is_in_static_data.c -opaque simple_float_const_opaque.ml
+
 CASES=fib tak quicksort quicksort2 soli \
-      arith checkbound tagged-fib tagged-integr tagged-quicksort tagged-tak
+      arith checkbound tagged-fib tagged-integr tagged-quicksort tagged-tak \
+      catch-try catch-rec even-odd even-odd-spill pgcd
 ARGS_fib=-DINT_INT -DFUN=fib main.c
 ARGS_tak=-DUNIT_INT -DFUN=takmain main.c
 ARGS_quicksort=-DSORT -DFUN=quicksort main.c
@@ -142,27 +79,78 @@ ARGS_tagged-fib=-DINT_INT -DFUN=fib main.c
 ARGS_tagged-integr=-DINT_FLOAT -DFUN=test main.c
 ARGS_tagged-quicksort=-DSORT -DFUN=quicksort main.c
 ARGS_tagged-tak=-DUNIT_INT -DFUN=takmain main.c
+ARGS_staticalloc=-I $(OTOPDIR)/utils config.cmx
+ARGS_catch-try=-DINT_INT -DFUN=catch_exit main.c
+ARGS_catch-rec=-DINT_INT -DFUN=catch_fact main.c
+ARGS_even-odd=-DINT_INT -DFUN=is_even main.c
+ARGS_even-odd-spill=-DINT_INT -DFUN=is_even main.c
+ARGS_pgcd=-DINT_INT -DFUN=pgcd_30030 main.c
 
-tests: $(CASES:=.o)
-	@for c in $(CASES); do \
-	  printf " ... testing '$$c':"; \
-	  $(MAKE) one CC="$(CC) $(CFLAGS)" NAME=$$c; \
+skips:
+	@for c in $(CASES) $(MLCASES) $(MLCASES_FLAMBDA); do \
+	  echo " ... testing '$$c': => skipped"; \
 	done
 
+one_ml:
+	@$(OCAMLOPT) $(ARGS_$(NAME)) -o $(NAME).exe $(NAME).ml && \
+	./$(NAME).exe && echo " => passed" || echo " => failed"
+
+one_ml_flambda:
+	@if $(FLAMBDA); then \
+	   $(OCAMLOPT) $(ARGS_$(NAME)) -o $(NAME).exe $(NAME).ml && \
+	   ./$(NAME).exe && echo " => passed" || echo " => failed"; \
+	 else \
+	   echo " => skipped"; \
+	 fi
+
 one:
-	@$(CC) -o $(NAME).out $(ARGS_$(NAME)) $(NAME).o $(ARCH).o \
+	@$(call CC,$(NAME).out $(ARGS_$(NAME)) $(NAME).$(O) $(ARCH).$(O)) \
 	&& echo " => passed" || echo " => failed"
 
 clean: defaultclean
-	@rm -f ./codegen *.out
+	@rm -f ./codegen *.out *.out.manifest *.$(O) *.exe
 	@rm -f parsecmm.ml parsecmm.mli lexcmm.ml
 	@rm -f $(CASES:=.s)
 
 include $(BASEDIR)/makefiles/Makefile.common
 
-power.o: power-$(SYSTEM).o
-	@cp power-$(SYSTEM).o power.o
+ifeq "$(CCOMPTYPE)-$(ARCH)" "msvc-amd64"
+# these tests are not ported to MSVC64 yet
+SKIP=true
+else
+SKIP=false
+endif
+
+ifeq "$(WITH_SPACETIME)" "true"
+# These tests have not been ported for Spacetime
+SKIP=true
+endif
+
+ifeq ($(CCOMPTYPE),msvc)
+CC=set -o pipefail ; $(NATIVECC) $(CFLAGS) /Fe$(1) | tail -n +2
+CFLAGS=$(NATIVECCCOMPOPTS)
+else
+CC=$(NATIVECC) $(CFLAGS) -o $(1)
+CFLAGS=$(NATIVECCCOMPOPTS) -g
+endif
+tests: $(CASES:=.$(O))
+	@for c in $(CASES); do \
+	  printf " ... testing '$$c':"; \
+	  $(MAKE) one NAME=$$c; \
+	done
+	@for c in $(MLCASES); do \
+	  printf " ... testing '$$c':"; \
+          $(MAKE) one_ml NAME=$$c; \
+        done
+	@for c in $(MLCASES_FLAMBDA); do \
+	  printf " ... testing '$$c':"; \
+          $(MAKE) one_ml_flambda NAME=$$c; \
+        done
 
 promote:
 
-arch: $(ARCH).o
+arch: $(ARCH).$(O)
+
+i386.obj: i386nt.asm
+	@set -o pipefail ; \
+	$(ASM) $@ $^ | tail -n +2
